#!/bin/zsh

MAX=$(cat /sys/class/backlight/intel_backlight/max_brightness)
CURRENT=$(cat /sys/class/backlight/intel_backlight/actual_brightness)
OPTION=$1

VALUE=$2

if [[ $1 == "set" ]]; then
    echo $(bc <<< "$MAX * $VALUE / 100.0") > /sys/class/backlight/intel_backlight/brightness
    exit
elif [[ $1 == "inc" ]]; then
    echo $(bc <<< "$CURRENT + $MAX * $VALUE / 100.0") > /sys/class/backlight/intel_backlight/brightness
    exit
elif [[ $1 == "dec" ]]; then
    echo $(bc <<< "$CURRENT - $MAX * $VALUE / 100.0") > /sys/class/backlight/intel_backlight/brightness
    exit
else
    echo Invalid argument: $1
fi
