#!/bin/sh

FILE=$1
NAME="${FILE%.*}"
EXTENSION="${FILE##*.}"

case $EXTENSION in
    ms)
        groff -et -ms $FILE -Tps -U | ps2pdfwr - $NAME.pdf
        ;;
    cc)
        g++ -Wall -g -o a.out $FILE && gdb a.out
        ;;
    rmd)
        echo "require(rmarkdown); render('$FILE', 'pdf_document')" | R --vanilla
        ;;
    *)
        ;;
esac
