#!/bin/sh

FILE=$1

xwinwrap \
    -g 3840x2160+0+0 \
    -ni \
    -st \
    -sp \
    -nf \
    -b \
    -un \
    -ov \
    -- mpv \
    -wid WID \
    $1 \
    --no-osc \
    --no-osd-bar \
    --loop-file \
    --player-operation-mode=cplayer \
    --no-audio \
    --panscan=1.0 \
    --no-input-default-bindings \
    --hwdec \
    --geometry=3840x2160+0+0 &

xwinwrap \
    -g 1920x1080+3840+0 \
    -ni \
    -st \
    -sp \
    -nf \
    -b \
    -un \
    -ov \
    -- mpv \
    -wid WID \
    $1 \
    --no-osc \
    --no-osd-bar \
    --loop-file \
    --player-operation-mode=cplayer \
    --no-audio \
    --panscan=1.0 \
    --no-input-default-bindings \
    --hwdec \
    --geometry=1920x1080+3840+0 &
