#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Set proper window sizes
/home/caden/.screenlayout/default.sh

#if path to liblinkt is not not exported do so:
if [ -z "$LD_LIBRARY_PATH" ]; then
  export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
fi

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# start eww daemon
eww daemon &

# Boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom --experimental-backends &> /dev/null &
  # picom &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton &> /dev/null &
fi

# Set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

# Set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/bg.png
fi
# if [ -x "$(command -v xsetroot)" ]; then
#   xsetroot -solid "#1e1e2e"
# fi

# Redshift start
redshift -P -x
redshift -r -l 42.358990:-71.058632 &

# Xbanish
xbanish &

# dunst
dunst -print &

# flameshot
flameshot &

#open eww 'bar' windows
#this is a bit of an uggly hack, a more elegant way will hopefully be possible with a future `eww` version
sleep 1
eww open nav
